# action.yml
name: 'Deploy MkDocs Rucio'
description: 'Deploys MkDocs Rucio site'
# Original author: 'Michael Hausenblas, hausenb@amazon.com'
branding:
  icon: 'arrow-up-circle'  
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
