site_name: Rucio Documentation test

nav:
    - 'index.md'
    - 'api.md'
    - 'clients.md'

theme:
  name: material

plugins:
    - search:
        separator: '[\s\-\.]+'

    - mkdocstrings:
      default_handler: python
      watch:
        - rucio/lib/rucio

repo_url: https://github.com/bari12/documentation_test/
